### ISSUE TITLE
Replace `lodash.get` with a smaller, modern implementation

### ISSUE THREAD

**Issue by binyamin** [11ty/webc#1]
The `lodash.get` package is 6 years old, so it can't use modern syntax. Therefore, it uses more code than we need. It's not huge, but we could do better. See [the package size on bundlephobia](https://bundlephobia.com/package/lodash.get@4.4.2).

There are a few implementations at https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_get.

**Comment by jabranr** [comment]
What sort of browser support we are looking for this? I might be able to push a PR for this.

**Comment by paulshryock** [comment]
> What sort of browser support we are looking for this? I might be able to push a PR for this.

Should browser support be [Browserslist's `default`](https://browsersl.ist/#q=defaults), and let consumers transpile as needed to their desired level of support?

**Comment by zachleat** [comment]
Instead of using lodash and lookup attributes, I think it’s prudent and more powerful to swap over to fully dynamic attributes instead! This is now on the readme and will ship with 0.3.0 https://github.com/11ty/webc#dynamic-attributes
