### ISSUE TITLE
Using script tags with absolute URLs as `src` attribute require a `webc:keep`

### ISSUE THREAD

**Issue by hsablonniere** [11ty/webc#10]
Hello @zachleat,

I used a `<script>` tag in the `<head>` of my main page with a `type="module"` and an absolute URL as source `src="https://example.com"`. This didn't work and I had to add a `webc:keep`.

I think I expected WebC to let them as is as it already does with `link` tags referring to external CSS files.

WDYT?

**Comment by zachleat** [comment]
Yeah, this is definitely a bug!

**Comment by zachleat** [comment]
This will ship with 0.2.0 tomorrow!

**Comment by zachleat** [comment]
You will be able to use `<script src>` and `<link rel="stylesheet" href>` to reference external assets and they’ll be compiled back into the JS and CSS for the components!

Or, you can use `webc:keep` to leave them as-is.
