### ISSUE TITLE
Attribute serialization doesn't handle quotes propertly

### ISSUE THREAD

**Issue by hsablonniere** [11ty/webc#11]
Hello @zachleat,

I tried to use some markup that involves using double quotes inside an attribute. Most of the time, I don't escape them and I use single quotes for the attribute like this:

```html
<div data-foo='foo="bar"'></div>
```

This works in any browser but going through WebC parsing and serializing, I end up with this:

```
<div data-foo="foo="bar""></div>
```

Which is parsed by browsers as:

* attribute name `data-foo` and value `foo=`
* attribute name `bar""` and value `` (empty string)

The "problem" comes from here I guess: https://github.com/11ty/webc/blob/main/src/attributeSerializer.js#L106

(edit) This code sample returns the same badly escaped/serialized output:

```html
<div data-foo="foo=&quot;bar&quot;"></div>
```

I guess parse5 serialization system could help.

WDYT?

**Comment by aturingmachine** [comment]
Took a quick stab at resolving this in #13.

**Comment by zachleat** [comment]
I merged #13 and I think it’s a great approach. This will go up with 0.2.0

**Comment by zachleat** [comment]
Just a note that `parse5` doesn’t report whether an attribute value is single or double quoted in the AST, so attribute values will be normalized to double quotes (if no nested quotes are in play)

**Comment by zachleat** [comment]
In 0.3.2 this will use the `entities` package to escape attributes properly. Thanks!
