### ISSUE TITLE
Ability to expand WebC components inside shadow roots

### ISSUE THREAD

**Issue by jaredcwhite** [11ty/webc#117]
Apologies if this is documented somewhere (and I know some things just changed in v0.9), but I'd like to be able to write declarative shadow DOM templates inside of `.webc` files and still get the ability to expand additional components in the template. From what I can tell, the WebC processing "magic" doesn't dive into the `<template shadowrootmode="open">` tag, which might be reasonable as a default but I'd definitely like to be able to switch it back on (maybe with another `webc:` directive of some kind)? TIA 😃

**Comment by zachleat** [comment]
HMMMMMMMMMMMMM yeah, I think you’re absolutely right here. WebC uses an implied `webc:raw` on declarative shadow DOM templates which hampers their power.

What we really want is an opt-out for asset bundling, I think? `webc:nobundle` so that stylesheets and scripts aren’t bundled.

**Comment by jaredcwhite** [comment]
@zachleat Yeah, I would expect style tags remain in place so they get sent over inside the DSD template.

**Comment by zachleat** [comment]
Removing implicit `webc:raw` on Declarative Shadow DOM nodes and adding an implicit `webc:nobundle` here—this shouldn’t require app code changes to keep current behavior.
