### ISSUE TITLE
Authoring webc files: advised way to get syntax highlighting?

### ISSUE THREAD

**Issue by nielsbom** [11ty/webc#130]
Hi!

Is this basically telling our editors "this is an HTML file" and then let them syntax highlight using those settings? Maybe a nice one for the README and docs?

**Comment by zachleat** [comment]
Yeah, that would be great! Do you want to contribute this as a PR?

**Comment by nielsbom** [comment]
Let me know if there's a better place or other places it needs to be added too.

**Comment by nielsbom** [comment]
Let's close this issue and continue in the PR.
