### ISSUE TITLE
Conditional rendering

### ISSUE THREAD

**Issue by radum** [11ty/webc#14]
Hello, first of all thank you for this. Its amazing.

I have a question about how one could go on and about to do conditional rendering of markup inside of a component.

There is not current mechanism and was wondering if this should be part of the JE rendering option or via a transform?

IMHO both options are not ideal and I guess some internal mechanism could be applied. But then again will not be easy to consider what data goes in the IF. It can't be stuff from the script tag as that is for client work.

Using IFs only with props might not be powerful enough to make it work it I think. Not sure if this should be in scope or not.

**Comment by zachleat** [comment]
https://github.com/11ty/webc#javascript-render-functions is the built-in way but I assume you’re wanting a declarative way to do it?

I would note that the upcoming Eleventy plugin will make using other Eleventy template syntaxes more seamless via transforms (see https://github.com/11ty/webc#custom-transforms)

**Comment by radum** [comment]
Thank you @zachleat I thought as much. Was wondering if there is something cooking that I don't know about.

And yes was thinking of a declarative way to do it. Looking fwd for the 11ty plugin.
