### ISSUE TITLE
Please don’t publish docs for unpublished features

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/webc#140]
I spent a good few hours wondering why `webc:for` wasn’t working; turns out that while the documentation shows this feature, `v0.9.4` hasn’t been published yet.

(Or at least make it clearer that you need to install directly from GitHub, or similar messaging)

**Comment by mattstein** [comment]
I’m in the same boat and setting up a [test case](https://github.com/mattstein/eleventy-foor-loop-example). Hasn’t `v0.9.4` [been published](https://github.com/11ty/eleventy-plugin-webc/releases/tag/v0.9.4) though?

**Comment by mattstein** [comment]
...and then I thought maybe you meant published to npm, but it’s [up to date there too](https://www.npmjs.com/package/@11ty/eleventy-plugin-webc). 🤔

**Comment by zachleat** [comment]
😭 oh goodness, I’m sorry!

**Comment by zachleat** [comment]
Put some pre-release warnings up!
