### ISSUE TITLE
Style scoping bug when moving to v0.11.x

### ISSUE THREAD

**Issue by cssandstuff** [11ty/webc#154]
Given two webc components
**c-red.webc**
```
<div webc:root="override">
  <slot></slot>
</div>

<style webc:scoped>
  :host {
    background-color: red;
  }
</style>
```

**c-blue.webc**
```
<div webc:root="override">
  <slot></slot>
</div>

<style webc:scoped>
  :host {
    background-color: blue;
  }
</style>
```

and their usage:
**page.webc** 
``` 
<c-red>Hi I am red</c-red>
<c-blue>Hi I am blue</c-blue>

<c-red>
  I am red.
  <c-blue>Hi I am blue</c-blue>
  still red
</c-red>

<c-blue>
  I am blue.
  <c-red>Hi I am red</c-red>
  still blue
</c-blue>
```

Prior to v0.11
would result in:
```
<div class="wpqw-v5wk">
  Hi I am red
</div>
<div class="wxarocnxj">
  Hi I am blue
</div>

<div class="wpqw-v5wk">
  I am red.
  <div class="wxarocnxj">Hi I am blue</div>
  still red
</div>

<div class="wxarocnxj">
  I am blue.
  <div class="wpqw-v5wk">Hi I am red</div>
  still blue
</div>

.wxarocnxj{background-color:blue}
.wpqw-v5wk{background-color:red}
```

but after moving to v0.11
it results in the same html but extra/borked css styles, it seems like the :host selector leaks upwards (if that makes any sense).
```
.wxarocnxj{background-color:blue}
.wpqw-v5wk{background-color:blue}
.wpqw-v5wk{background-color:red}
.wxarocnxj{background-color:red}
```

**Comment by cssandstuff** [comment]
I guess the clearer description is that if you style using :host in a component and you using that component in another (via a slot) then the :host css for that component makes its way into the parent somehow.

**Comment by rijkvanzanten** [comment]
I just noticed the same behavior. `:host` seems to "bubble up" to the highest parent, meaning that things like `:host > div` behave erratically

**Comment by zachleat** [comment]
apologies, I think this may be the regression introduced in #152 but I will investigate further.

**Comment by zachleat** [comment]
I did confirm that this is fixed by #152 with the test case you supplied, thank you!

Shipping with v0.11.2 today.

**Comment by rijkvanzanten** [comment]
Thanks @zachleat! Killing it as always 🚀

**Comment by zachleat** [comment]
Thank you @rijkvanzanten!!
