### ISSUE TITLE
Allow for webc:nokeep in the component itself

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/webc#158]
I've got a component where I never want it to show up in the HTML. To do this, I have to add code to the _calling_ template, like so:

```
<myawesomecomponent webc:nokeep></myawesomecomponent>
```

That works, but it would be nice if the component could set this itself, perhaps in front matter. Imagine a webc component I'm sharing with others. I want it to be as simple to use as possible. Being able to set this myself means less typing for the user.

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/languages/webc/#override-the-host-component-tag does most of this, I think!

**Comment by cfjedimaster** [comment]
This is not quite what I mean. So my component is named lightbox. When I leave it in the DOM, I end up with:

```html
<html>
<body>
<!--StartFragment-->

<lightbox images="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]"><div class="lightbox_images">
stuff here
</div></lightbox>
</body>
</html>
``

Using webc:nokeep on the calling doc completely removes it. If I use override, I can *replace* it with my top level div, but I still have images=object etc. 

I'm only bugged about this as I need to use a :attribute as my data is complex, not a string. (FYI, this is not a blocker for me. I'm using scoped css so I'll need a top level tag anyway, but still curious.)

**Comment by cfjedimaster** [comment]
Ehh - forgot about `:@` to make it private. Disregard again, 0 for 2 today, but learned stuff. :)
