### ISSUE TITLE
getBundle not working

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/webc#159]
I'm filing this here and not in the getBundle repo as I assume it's an issue with WebC's use of the other project. I've got a component with a script tag in it. It gets bundled up fine. In Liquid, I'm trying to use it like so:

```
<script>
{{ getBundle "js"}}
</script>
```

This returns an empty string (between the script tags). Yet this deprecated code still works:

```
<script>{{ page.url | webcGetJs }}</script>
```

**Comment by zachleat** [comment]
`{% getBundle "js" %}` is the syntax!

**Comment by cfjedimaster** [comment]
I could have *sworn* I tried this - sorry!

**Comment by zachleat** [comment]
It’s really no worries at all! Easy mistake, easy fix!
