### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mmatuzovic** [11ty/webc#20]
I've been starring at the README files of webc and 11ty-plugin-wc for the past 2 hours and now I have questions. I hope this is the right place to ask them. 

Did I understand correctly that webc…
…can be as simple as an alternative to shortcodes (in nunjucks, etc.)?
…can be an alternative to includes/macros?
…is super awesome because it gives us SFC without being dependent from a framework?

It's kinda like working with web components without necessarily shipping them to the client. Great DX but no/less JS for the user, right? If that assuption is right, how does it integrate with actual web components. Like when I do want to ship web components. Would I use webc for that? No, right? I can but it's not primarily intended for that. It's not a replacement for something like lit? 
Can I use a web component I've written somewhere else and use webc to compile it to HTML?

It'd be great if you could help me answer these questions. Thank you! ❤️

**Comment by zachleat** [comment]
I did finally ship the Eleventy plugin! https://github.com/11ty/eleventy-plugin-webc

https://twitter.com/eleven_ty/status/1574836979681955846 included a crash course video: https://www.youtube.com/watch?v=X-Bpjrkz-V8

I think your understanding is correct! This adds components to Eleventy using web components HTML standards. WebC components are processed into expanded HTML.

The best use case is that in your content you can use a component `<my-component>` and then in your component definition for `my-component.webc` you can include a bunch of child content that you don’t want to have to duplicate every time you want to use the component. Gives you a nice authoring experience without having to copy and paste fallback content everywhere.

That said, WebC components can have clientside interactivity! Just include the clientside JS you’d normally use to register the component (you could also put this in your WebC component definition too) and it’ll get bundled up with the rest of the JS.

What WebC _doesn’t_ is that it won’t compile server-side rendered markup from an existing non-WebC web component. That’s a bit too performance intensive during the build and doesn’t give you a reliable enough progressive enhancement story (imo). I don’t necessarily want full SSR, I want the option of going full PE and setting those PE boundaries explicitly (if that makes sense)

Let me know if you have any other specific questions!

**Comment by mmatuzovic** [comment]
That's perfect, Zach. Thank you!
