### ISSUE TITLE
VS Code HTML highlight doesn't know WebC's @-prefixed properties

### ISSUE THREAD

**Issue by Miu8** [11ty/webc#210]
![props](https://github.com/11ty/webc/assets/90461493/0a0e6dd3-8875-48f0-9506-9d41f611b3a3)

**Comment by vanarok** [comment]
Perhaps this extension will help: https://github.com/hawkticehurst/webc-vscode. I didn't test highlighting with it because I only ran the language server from the repository in the Helix editor, and it worked well.
