### ISSUE TITLE
Ability to use WebC components as client-side custom elements?

### ISSUE THREAD

**Issue by Paul-Hebert** [11ty/webc#22]
Hey @zachleat ,

This is super, _super_ cool! I'm excited to play with it. 

I have a project at work that I _think_ this may be a good match for, but I'm not 100% sure if I understand correctly.

For the project, we're going to be making a handful of components that will be used in a variety of different server environments (PHP, Ruby, Node)

In a perfect world I'd like to provide component consumers with a couple of options for using these components:

1. Hit an API endpoint that would return the HTML, JS, and CSS necessary for rendering the component. They can use these to build their page server-side.
2. Alternately, allow them to include a script and then use the web components as native client-side custom elements (e.g. add `my-component` in their markup and have the component render client-side without SSR.)

From reading the README it seems like WebC would be an excellent fit for the first use case, but it's not clear to me whether it would work for the second use case.

Is WebC meant to support both of those use cases or is it just focused on the first?

Thanks!

**Comment by zachleat** [comment]
I don’t think WebC will likely support the use case where you don’t use a build to compile the optimized markup. I don’t think it’d be a good investment of time to try to do “isomorphic” components that can render on the client or the server (though that would be possible, WebC is simple enough that it could run in a browser with minimal repackaging 👀). I just don’t think that will produce output that I would want Eleventy to produce. I’d rather see Eleventy operate in Serverless or Edge rendering where you wouldn’t have to do clientside stuff. (My opinion on this may change if WebC gets more popular 😅, I can definitely see some use cases in CMS-land where it’d be nice to have WebC rendering for client previews? Not sure yet!)

All that said, I do want to plug the latest tutorial that shows how to use clientside interactive web components with Eleventy, which hopefully is of some interest to you! https://www.youtube.com/watch?v=p0wDUK0Z5Nw

Let me know if you have more questions!

**Comment by Paul-Hebert** [comment]
Thanks @zachleat !

That makes sense. I totally understand focusing on the Serverless/Edge use case. 

I appreciate you taking the time to answer, and I'm excited to get a chance to play with this. That's a great tutorial. WebC seems like a great authoring experience, especially when coupled with 11ty. (Makes me want to start redesigning my personal site again 😅 )
