### ISSUE TITLE
webc file is compiled incorrectly when DOCTYPE definition is written in capitals. 

### ISSUE THREAD

**Issue by dwkns** [11ty/webc#24]
When a doctype definition in a webc file is in capitals it doesn't compile correctly. Lines are stripped out. 

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>doctype is lowercase</title>
</head>
<body>
</body>
</html>
```

compiles to 
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>doctype is lowercase</title>
</head>
<body>

</body>
</html>
```
as expected. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DOCTYPE IS CAPITAL</title>
</head>
<body>
</body>
</html>
```

Compiles to 

```html

  <meta charset="utf-8">
  <title>DOCTYPE IS CAPITAL</title>



```
The only difference is that DOCTYPE is capital rather than lowercase.

Repo to reproduce:
https://github.com/dwkns/11ty-webc-doctype-issue/

**Comment by zachleat** [comment]
Oop, yeah! Easily fixable, stand by.

**Comment by zachleat** [comment]
Shipping with WebC v0.4.4.

Note that the output normalizes to lowercase `<!doctype html>` but it’s compiling correctly. If you feel strongly about preserving the case of the doctype, please file an additional issue!

Thanks!
