### ISSUE TITLE
Specifying default behavior of `webc:nokeep` vs `webc:keep`

### ISSUE THREAD

**Issue by mayank99** [11ty/webc#26]
It would be nice to be able to change the default behavior of whether the host element is kept around.

Imagine you're building a reusable `my-button` component. With the following webc file:
```html
<button><slot></slot></button>

<style webc:scoped>
  button {
    background: thistle;
    font: inherit;
  }
</style>
```

It should be possible to use it like so without keeping the host element around.
```html
<my-button>Hi</my-button>
```

The above should evaluate to the following html and css:
```html
<button class='c9dv8a'>Hi</button>
```
```css
.c9dv8a {
  background: thistle;
  font: inherit;
}
```
---

This could be done via an option similar to how `setBundlerMode` changes the default aggregration behavior. Naming could get weird though (`setKeep`? `setNoKeep`? `removeHostByDefault`?)

The motivation is to make it easier (i.e. by not having to repeat `webc:nokeep`) to reuse pieces of markup without adding unnecessary elements in the resulting html.

**Comment by zachleat** [comment]
Yeah! I did fix a bug with this _very recently_ using the `webc:root` directive, this should do what you want:

```
<button webc:root webc:keep><slot></slot></button>

<style webc:scoped>
  button {
    background: thistle;
    font: inherit;
  }
</style>
```

**Comment by zachleat** [comment]
https://github.com/11ty/webc/commit/6418a57dc679ef49b31e701660e3ed746f420bf4
https://github.com/11ty/webc/commit/d7dab455413e7ac3654f899244940ae84a0cfbac

**Comment by zachleat** [comment]
Oh, after another re-read I missed the larger point 😅 Lemme think on it a bit!

**Comment by mayank99** [comment]
Wait I think this does exactly what I want. I didn't realize I could use `webc:keep` and `webc:root` together.

Defining this:
```html
<button webc:root webc:keep><slot></slot></button>

<style webc:scoped>
  :host { /* button doesn't work here but that's fine */
    background: thistle;
    font: inherit;
  }
</style>
```

allows me to use it like this:
```html
<my-button>Hi</my-button>
<my-button>Hi</my-button>
```

The goal was to make "usage" easier (not having to repeat `webc:nokeep` in every instance), so having extra attributes in the definition is a fine tradeoff and I don't think a config option is necessary.

Thank you for the suggestion 💜

**Comment by zachleat** [comment]
Great news! Thanks!

**Comment by ztiromoritz** [comment]
Found this thread, while searching with the same intend.
Since Version 0.9.0 you have to use **webc:root="override"** like this:
```
<button webc:root="override"><slot></slot></button>
<style web:scoped> :host {/*...*/ } </style>
```
Documentation: [https://www.11ty.dev/docs/languages/webc/#override-the-host-component-tag](https://www.11ty.dev/docs/languages/webc/#override-the-host-component-tag)
