### ISSUE TITLE
@html overrides CSS/JS asset aggregation

### ISSUE THREAD

**Issue by darthmall** [11ty/webc#29]
Not sure what I’m doing wrong here. I’m experimenting with an all-WebC Eleventy site. I have a [hero-block component](https://github.com/darthmall/webc-eleventy-test/blob/main/src/components/hero-block.webc) that is declaring some styles, I have a couple of layouts (chained together), and in the [base layout](https://github.com/darthmall/webc-eleventy-test/blob/main/src/layouts/base.webc#L15) I have a style tag that is settings its contents to `this.getCSS(this.page.url)`. But no styles are in the built HTML.

Not sure what I’m missing…

Here’s the full project that you can clone and test: https://github.com/darthmall/webc-eleventy-test

**Comment by darthmall** [comment]
I _just_ figured this out and was coming over to here to close this as user error, but I’m glad it was an actual bug and not a total waste of your time. 😄 

A workaround is to use a `<template webc:nokeep>`:

```html
<hero-block>
  <template @html="this.site.title" webc:nokeep></template>
</hero-block>
```

**Comment by zachleat** [comment]
I know I said I’d get to it this week but I didn’t quite make it, sorry! This is still on deck!

**Comment by darthmall** [comment]
Don’t sweat it. There’s a workaround. It’s not for anything critical. 😃

**Comment by zachleat** [comment]
Some other benefits shaken out here by this fix:

* we now treat the return value from `@html` on a host component as default slot content that can be consumed by the component definition.
* this reprocesses `@html` return values as WebC content too.

**Comment by zachleat** [comment]
shipping with v0.5.0!
