### ISSUE TITLE
Preserve slotted elements in named slots

### ISSUE THREAD

**Issue by knowler** [11ty/webc#3]
Currently, slotted elements are not preserved in named slots. `webc:keep` doesn't seem to work.

Example component definition:

```html
<!-- components/my-article.webc -->
<article>
  <hgroup>
    <slot name="title"></slot>
    <slot name="subtitle"></slot>
  </hgroup>
  <prose-content>
    <slot></slot>
  </prose-content>
</article>
```

Example component usage:

```html
<!-- page.webc -->
<my-article>
  <h2 slot="title">Article Title</h2>
  <p slot="subtitle">Subtitle</p>
  <p>Content</p>
</my-article>
```

Expected compilation:

```html
<article>
  <hgroup>
    <h2>Article Title</h2>
    <p>Subtitle</p>
  </hgroup>
  <prose-content>
    <p>Some content.</p>
  </prose-content>
</article>
```

Actual compilation:

```html
<article>
  <hgroup>
    Article Title
    Subtitle
  </hgroup>
  <prose-content>
    <p>Some content.</p>
  </prose-content>
</article>
```

By default, I would expect that the slotted elements in the named slots be preserved as they are preserved in the unnamed slot. I also think that there should be someway to preserve the `slot` attribute on the slotted elements as well, whether that be the default or if there was an option for it.

**Comment by zachleat** [comment]
Just a regular web components confirmation on the behavior here: https://codepen.io/zachleat/pen/gOeJxOP/b166c63a7f4b4950db8ccd8c2bcd505d?editors=1010

Stand by for fix

**Comment by zachleat** [comment]
Didn’t finish this one today but I am still working on it!

**Comment by zachleat** [comment]
Gonna cut a 0.2.0 with this in the next day or two!
