### ISSUE TITLE
Congrats and a few questions (not an issue)

### ISSUE THREAD

**Issue by Brixy** [11ty/webc#30]
Hi Zach and maintainers,

thanks a lot. This seems to be a ‘big thing’!

I have never looked in Vue, React et al. because an SSG + vanilla JS is just enough. But WebC has piqued my interest.

Although I understand your tutorials and how to set up WebC components, a few questions come to my mind.

- (How) is it possible (and would it make sense) to drop Nunjucks/Liquid completely in favour of WebC?
- If possible will a simple example template be provided?
- How does WebC relate to [11ty \<is-land\>](https://github.com/11ty/is-land), and will WebC replace it?
- Can Eleventy + WebC replace a web framework (for those interested)?

Sorry—this a rather a discussion contribution than an issue. Thank you! I hope my questions are not too incompetent.

**Comment by zachleat** [comment]
1. Yes! Leaning on JavaScript render functions should get you most of the way there as an escape hatch for advanced things https://github.com/11ty/webc#javascript-render-functions
2. Do you mean a repo?
3. No, this will complement `<is-land>` and work together!
4. Yeah, absolutely!

I’d check out the recently launched 11ty.dev docs for this: https://www.11ty.dev/docs/languages/webc/ which has the two intro videos and my last blog post from the talk this week https://www.zachleat.com/web/webc-in-eleventy/

Hope that helps!
