### ISSUE TITLE
Avoid parsing template contents as html before passing to transform function

### ISSUE THREAD

**Issue by WickyNilliams** [11ty/webc#48]
I was playing around building a custom transform, and i noticed that the innards of the template seem to get parsed as html and then passed to to the transform function, rather than the raw content. For example:

```html
<template webc:type="custom">
  <foo id={this.uid}>test</test>
</template>
```

If I've registered a custom transform like

```js
page.setTransform("custom", content => console.log(content))
```

The content I receive has already been processed, so we see in the logs:

```html
<foo id="{this.uid}">test</test>
```

Notice the quotes around the curly braces that weren't there before. If possible it would be nice to receive the raw, untouched contents, which can later be parsed after I have transformed it.

**Comment by zachleat** [comment]
Curious if you tried mixing this with webc:raw?

**Comment by WickyNilliams** [comment]
I didn't! I'll try next time I'm at the computer. Does raw prevent reprocessing? If raw fixes it, it would be nice to be able to configure a specific transform to default to raw like

```js
page.setTransform(myTransform, { raw: true })
```

**Comment by WickyNilliams** [comment]
Just tested, the result is the same even with `webc:raw`

**Comment by zachleat** [comment]
Uncovered a pretty hefty bug with raw `<template>` here, thank you! `<template>` (when used _without_ `webc:root`) will now return the raw preparsed input!

Shipping with the next version (probably 0.6)

**Comment by WickyNilliams** [comment]
Amazing! Thank you. Does this mean I should or shouldn't use `webc:raw`?

**Comment by zachleat** [comment]
Shipped with `0.5.4`. Just `<template webc:type>` should suffice but this will also fix how we handle `<template webc:raw>` too!

**Comment by WickyNilliams** [comment]
Lovely stuff. Appreciate it

**Comment by zachleat** [comment]
Thank you!
