### ISSUE TITLE
`@raw` for raw content to partner with how `@html` reprocesses as WebC

### ISSUE THREAD

**Issue by zachleat** [11ty/webc#51]
Alternative to `@html` which now reprocesses content via #33  Docs: https://www.11ty.dev/docs/languages/webc/#@html

Maybe it should be named `@raw` because it is similar to how `<template webc:raw>` works

**Comment by zachleat** [comment]
I like that a lot @dz4k!

**Comment by zachleat** [comment]
Just to circle back, these are still on the table here but in v0.6.0 `<* webc:raw @html>` will work as I think we expect `@raw` would here (though `@raw` is not yet added)

**Comment by dz4k** [comment]
I still think `@text` is necessary for any component dealing with untrusted (or just non-HTML) data.

**Comment by zachleat** [comment]
v0.6.0 will ship with `@text`—thanks!!
