### ISSUE TITLE
docs imply <html> etc added for you 

### ISSUE THREAD

**Issue by WickyNilliams** [11ty/webc#54]
In the section of the readme "html imports (kidding... kinda)" it is implied that the `<html>`, `<!doctype>` etc get added for you but this doesn't appear to the case. Given the following, as described in the readme:

page.webc:

```html
<title>WebC Example</title>
<my-component></my-component>
```

components/my-component.webc":

```html
Components don’t need a root element, y’all.
```

and the following JS:

```js
import { WebC } from "@11ty/webc";

let page = new WebC();

page.defineComponents("components/**.webc");
page.setInputPath("page.webc")

const { html } = await page.compile()
console.log(html)
```

the docs say:

> compiling page.webc will return the following HTML:

```html
<!doctype html>
<html>
	<head>
		<title>WebC Example</title>
	</head>
<body>
	Components don’t need a root element, y’all.
</body>
</html>
```

I do not see `<doctype>` etc in the output, i just see:

```html
<title>WebC Example</title>
Components don’t need a root element, y’all.
```

Here's a stackblitz showing the issue. Check the output of the console https://stackblitz.com/edit/webc-html-doc-type-added

Wondering if this is a bug or a docs issue?

**Comment by zachleat** [comment]
Ah, yeah. I think that’s a docs issue. WebC has two rendering modes: `component` and `page`. Component is for component fragments and page is the one you’re expecting here.

https://github.com/11ty/webc/blob/7e4558ba45c1b7b495c2a4e801181528c8e66dc9/webc.js#L61

I think the safest thing is to update the docs to include a doctype for these examples, but starting them with `html` would work too.

The other point of discussion might be if it’s worthwhile to add another check for `<title>` but my vote would be no 😅

**Comment by zachleat** [comment]
Docs updates are deploying, thank you!

**Comment by WickyNilliams** [comment]
Ah ok, now I get it. Wondering if the two modes should be noted anywhere? It's sort of implied with the changes you made to the docs, but something explicit would be useful to have written down

**Comment by zachleat** [comment]
Filed at #64 thanks!
