### ISSUE TITLE
@html prop renders unexpected tags

### ISSUE THREAD

**Issue by rianmurnen** [11ty/webc#57]
Using the `@html` prop on an element _outside_ a `<template>` behaves as expected. But when `@html` is applied _inside_ a `<template>` the component instance is rendered with unexpected `<html>`, `<head>`, and `<body>` elements.

Package `package.json`

```json
{
  "name": "learn-webc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npx @11ty/eleventy",
    "start": "npx @11ty/eleventy --serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@11ty/eleventy": "^2.0.0-canary.16",
    "@11ty/eleventy-plugin-webc": "^0.5.1"
  }
}
```

Config `.eleventy.js`

```js
const pluginWebc = require("@11ty/eleventy-plugin-webc");

module.exports = function(eleventyConfig) {
	eleventyConfig.addPlugin(pluginWebc, {
		components: "_includes/webc/*.webc"
	});
};
```

Layout `layout.webc`

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
</head>
<body>
<div webc:nokeep @html="content"></div>
</body>
</html>
```

Page `page.webc`

```html
---
layout: layout.webc
---
<my-test @text="text"></my-test>
```

Web Component `my-test.webc`

```html
<div @html="text"></div>
<template>
    <div @html="text"></div>
</template>
```

## Output

The output as viewed in a text editor, not the browser dev tools. The browser seems to ignore and strip the unexpected elements but they are present in the actual generated file.

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
</head>
<body>
<div>text</div>
<template>
    <div><html><head></head><body>text</body></html></div>
</template>
</body>
</html>
```

I had the same experience when I downloaded [11ty/demo-webc-counter](https://github.com/11ty/demo-webc-counter ) and ran it without any modification.

**Comment by zachleat** [comment]
Also reported by @jonathantneal on Twitter https://twitter.com/zachleat/status/1585715141198639105

**Comment by zachleat** [comment]
Regression from #34

**Comment by zachleat** [comment]
This will ship with the next version!
