### ISSUE TITLE
Question - Will script tags be parsed further?

### ISSUE THREAD

**Issue by thetutlage** [11ty/webc#6]
This is more of a question to understand how Webc plans to handle the `script` tags inside a file. Given the following template.

```html
<!doctype html>
<html lang="en">
  <body>
    <p> Hello world </p>
  </body>
</html>

<script>
  import Alpine from 'alpine'
  Alpine.start()
</script>
```

Right now, the contents of the `script` tag are returned as it is. Are there any plans to further process the scripts and return a compiled version of them? Or is it something that should be handled using a custom transform?

**Comment by zachleat** [comment]
WebC aggregates `<script>` elements found in component definitions into the `js` prop returned from the `compile` method.

This is what I see from your test:

```js
{
  html: '<!doctype html>\n' +
    '<html lang="en">\n' +
    '<head></head><body>\n' +
    '    <p> Hello world </p>\n' +
    '  \n' +
    '\n' +
    '\n' +
    '</body>\n' +
    '</html>',
  css: [],
  js: [ "\n  import Alpine from 'alpine'\n  Alpine.start()\n" ],
  components: [ 'issue-6.webc' ]
}
```

If you want to change this behavior, you can use `<script webc:keep>` attribute to leave the script as-is!
