### ISSUE TITLE
How do I read props?

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/webc#62]
The docs note that you can declare private props on webc components using the special `@` syntax, but they don't clarify how to access this data in JavaScript:

> Make any attribute into a prop by prefixing it with @. Props are “private” attributes that don’t end up in the output HTML (they are private to WebC). They will be filtered from the output HTML but are available to the component’s data.

This is the example from the docs:

```html
<my-component @propName="Hello"></my-component>
```

1. Where is `propName` accessible in the web component?
2. Do we still need to use `@` wherever we access it in JavaScript or do we drop that?

**Comment by AleksandrHovhannisyan** [comment]
Sorry, duplicate of https://github.com/11ty/eleventy-plugin-webc/issues/23

**Comment by zachleat** [comment]
Example deploying to https://www.11ty.dev/docs/languages/webc/#props-(properties)

and on https://github.com/11ty/webc#properties-or-props

**Comment by voxpelli** [comment]
For future reference: `@propName` is accessed within the component as `propname`, not `propName`
