### ISSUE TITLE
Convert `attr-name` to `attrName` when referencing in data.

### ISSUE THREAD

**Issue by zachleat** [11ty/webc#71]
`parse5` enforces the HTML specification and converts both attributes and `@`-prefixed properties to lowercase

```
<my-component attrName="test" @propName="test">
```

(is referenced inside `my-component` as `attrname` and `propname` respectively).

First reported by @voxpelli: https://github.com/11ty/webc/issues/62#issuecomment-1313435541

I don’t know if we necessarily want to add to the parsing complexity but a nice workaround could be to convert dash names to camelcase:

e.g. `@prop-name` would be referenced as `propName` and `attr-name` would be referenced as `attrName`

Open for discussion here!

**Comment by zachleat** [comment]
Future note for me: the code for this is merged but disabled until 0.8.0

**Comment by zachleat** [comment]
Shipping with v0.8.0

**Comment by anghelos** [comment]
Is there any way to escape that for HTML `data-*` attributes? Say I want an attribute to be `data-image` and remain as such. Also see #178 and #163

**Comment by zachleat** [comment]
@anghelos this is filed at #216, fix shipping with v0.12.0-beta.1 on both @attributes and webc.renderAttributes, thank you!
