### ISSUE TITLE
11ty + webc doesn't work with webc:type="js"

### ISSUE THREAD

**Issue by phoebethewitch** [11ty/webc#78]
continuing from https://fediverse.catgirlin.space/notice/APpn2rG30p97SCx7wm

Trying to use a webc:type="js" like how the docs show doesn't work. 

Input: 
```html
---
layout: layout
---
<div>
	<p>normal component</p>
	<a-component></a-component>
	
	<p>js</p>
	<script webc:type="js">
		`<p>hi</p>`;
	</script>
	
	<p>js with component</p>
	<script webc:type="js">
		`<a-component></a-component>`;
	</script>
</div>
```

Output: 
```html
<!doctype html>
<html lang="en">
<head>
	...
	<title>WebC Example</title>
	<style></style>
	<script><p>hi</p>
<a-component></a-component></script>
</head>
<body><div>
	<p>normal component</p>
	woah i am component. i do things. 
	
	<p>js</p>
	
	
	<p>js with component</p>
	
</div></body>
</html>
```

`_components/a-component.webc`:
```html
woah i am component. i do things. 
```

Layout:
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>WebC Example</title>
	<style @raw="getCss(page.url)"></style>
	<script @raw="getJs(page.url)"></script>
</head>
<body @raw="content"></body>
</html>
```

---
unrelated, is there a way to pass the object like I was trying to do linked above?

**Comment by oliverjam** [comment]
Yeah I just hit this issue too. Spent ages frustrated wondering why this wasn't outputting _anything_:

```html
<script webc:type="js">
`hello`;
</script>
```

It's extra confusing because overriding a native element does work without (e.g. the `<img>` example in the docs).

Is it intended that we have to put `webc:is="template"` on every JS type component?

**Comment by zachleat** [comment]
There were some bugs here! Do note the test cases added here: https://github.com/11ty/webc/commit/62338b604f5fd8d3e1e5e502e088b6a7947f8f3e

But some of the examples I would *not* expect to work as is—I’ll amend the docs to try to make it more clear.
I think the big two takeaways I’m seeing are that:

1. `<script webc:type="js">` does not output a parent tag by default. You need to use `<script webc:type="js" webc:keep>` to re-use the parent tag (and it will respect `webc:is` moving forward)
2. IF you want to **reprocess** `<script webc:type="js">` as WebC, you do need to use a `template` element (via `<template webc:type="js">` or `<script webc:type="js" webc:is="template">`) as @last-arg notes. I did fix some bugs with regular-old-html here. You can also use `webc:keep` here too, if you’d like.

**Comment by zachleat** [comment]
@phoebethewitch can you file “unrelated, is there a way to pass the object like I was trying to do linked above?” separately? (thank you!)

**Comment by zachleat** [comment]
Note the changes to the docs here: https://github.com/11ty/11ty-website/commit/930f0dfe925db66be0d8a1dd8092ad7f30e5b992
