### ISSUE TITLE
webc:import is not relative to caller

### ISSUE THREAD

**Issue by Kalabasa** [11ty/webc#79]
Given this structure:
```html
// /pages/articles/my-page.webc
<my-component></my-component>
```

```html
// /components/my-component.webc
<any-tag-name webc:import="./other-component.webc"></any-tag-name>
<slot></slot>
```

```html
// /components/other-component.webc
<script>stub()</script>
```

The import `./other-component.webc` from `/components/my-component.webc` resolves into `/pages/articles/other-component.webc` (relative to my-page.webc) instead of `/components/other-component.webc` (relative to the caller, my-component).

**Comment by zachleat** [comment]
Reproduced!

**Comment by zachleat** [comment]
Shipping with WebC v0.8.0
