### ISSUE TITLE
Logs don't work in webc:type="js"

### ISSUE THREAD

**Issue by oliverjam** [11ty/webc#83]
Given that `<script webc:type="js">` components are for "arbitrary server JavaScript" I expected logs from inside the JS code to show up in my terminal build logs. Unless I'm missing something these appear to get swallowed. E.g.

```html
<script webc:type="js" webc:is="template">
  let message = 1 + 1;
  console.log({ message });
  "hello " + message;
</script>
```

This outputs "hello 2" but nothing is logged to my terminal.

**Comment by zachleat** [comment]
This will ship with WebC v0.8.0! Thanks!
