### ISSUE TITLE
Getting the <script> scope into @html evaluation

### ISSUE THREAD

**Issue by pauleveritt** [11ty/webc#87]
Imagine I have `hello.webc`:

```html
<p>
    <span @html="this.firstName">Hello</span>
</p>
<script>
    export const firstName="Zach";
</script>
```

I couldn't find an explanation of that is the scope inside the JS evaluation for `@html`.
It looks like `evaluateAttribute` is where the scope is collected:

```javascript
	// Used for @html and webc:if
	async evaluateAttribute(name, attrContent, options) {
		let data = Object.assign({}, this.helpers, options.componentProps, this.globalData);
		let content = await ModuleScript.evaluateScript(name, attrContent, data, {
			filePath: options.closestParentComponent || this.filePath
		});
		return content;
	}
```

**Comment by zachleat** [comment]
As also noted in #109:

`<script webc:setup>` will ship with WebC v0.9.0.

Has access to the standard stuff from the WebC data cascade: global data (Eleventy’s data cascade), helper functions, etc.

A few test cases here: https://github.com/11ty/webc/blob/efe23f6c12ac8505c52f9cfedc0bce6f4d0ad750/test/stubs/setup-script/test.js

* Any variable declarations or functions declared here will be available in the component (no need for export, just use a normal top-level variable declaration)
* Is async-friendly
* runs once per component (not once per instance, though the door is open for that later if we want it)
