### ISSUE TITLE
Helper function alwaysBlue not found

### ISSUE THREAD

**Issue by pauleveritt** [11ty/webc#88]
[This example](https://github.com/11ty/webc/blob/251c15642999aa29265a8728a779aab3133b67eb/examples/helpers/page.js) has the following:

```
import { WebC } from "@11ty/webc";

let page = new WebC();

page.setInputPath("page.webc");
page.setHelper("alwaysBlue", () => {
  return "I'm blue, da ba dee da ba di";
});

let { html, css, js, components } = await page.compile();
console.log(html);
```

Running this with 0.8.0 gives:

```
TypeError: this.alwaysBlue is not a function
```

**Comment by zachleat** [comment]
Did a comprehensive review (and some refactoring) of how the “WebC data cascade” works in different scenarios and made some small adjustments, noted below:

- `@html` and `@if` both use **ModuleScript.evaluateScript**
    - WebC data cascade
        - `...globalData` **********MOVED**********
        - `...helpers`
        - `...Component Props`
- `webc:type="js"` uses **ModuleScript.evaluateScript** and `webc:type="render"` uses **ModuleScript.getModule**, both with this format:
    - WebC data cascade
        - `filePath`
        - `helpers`
        - `slots`
        - **********ADDED********** `...helpers` (fixes this issue)
        - `...globalData`
        - `...Attributes`
        - `...Component Props`
- When serializing attributes
    - WebC data cascade
        - `...globalData` **********MOVED**********
        - `...helpers`
        - `...Component Props`
        - `...Host Component Data`

**Comment by zachleat** [comment]
Notably in current versions you need to use `this.helpers.alwaysBlue` in both `webc:type="js"` and `webc:type="render"`. But for consistency we’re adding those to the top level in WebC v0.9.0 too.
