### ISSUE TITLE
About the nameless render function

### ISSUE THREAD

**Issue by hsablonniere** [11ty/webc#9]
Hello @zachleat

(this project is really interesting BTW :heart_eyes:)

I was trying to use the render function example but I encountered something odd.

This works:

```html
<script webc:type="render" webc:is="template">
function() {
  return `Hello ${this.name}`;
}
</script>
```

but this does not:

```html
<script webc:type="render" webc:is="template">
function () {
  return `Hello ${this.name}`;
}
</script>
```

The difference: my IDE's formatter introduced a space between the function and parens and I got this error:

```
src/index.html:2
function () {
^^^^^^^^

SyntaxError: Function statements require a function name
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1049:15)
at Module._compile (node:internal/modules/cjs/loader:1084:27)
at ModuleScript.getModule (..../test-webc/node_modules/@11ty/webc/src/moduleScript.js:18:5)
at Object.render (..../test-webc/node_modules/@11ty/webc/src/ast.js:40:26)
at AstSerializer.transformContent (..../test-webc/node_modules/@11ty/webc/src/ast.js:498:41)
at AstSerializer.compileNode (..../test-webc/node_modules/@11ty/webc/src/ast.js:604:43)
at AstSerializer.getChildContent (..../test-webc/node_modules/@11ty/webc/src/ast.js:397:40)
at AstSerializer.compileNode (..../test-webc/node_modules/@11ty/webc/src/ast.js:678:46)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

In any JavaScript runtime, a function declaration without a name is an error. I think users will want to use their own tooling (formatters, linters...) on the `<script>` tags inside WebC files, having something really standard would be better IMO.

I looked at the source of https://github.com/11ty/webc/blob/main/src/moduleScript.js and I now understand how it works. You're using Node.js `module` module as a parser/runner and you add a `module.exports = ` prefix if necessary to make it work. Clever :wink: Being a value assigned to `module.exports`, the anonymous function is no longer an error.

I did a bit of digging;

* The `module._compile` function doesn't seem to be documented, won't this be a problem in the future?
* I tried to write `export default function () { /* ... */ }` but it seems like it doesn't work with ESM :cry:
* I wonder if the `vm` module would be a better fit for this
  * (edit) I tried `vm.Script`, it's basic but it could work even without declaring a function.
  * (edit) I tried `vm.Module` to rely on an ESM default export but it's experimental and not that easy to work with.

Even if you stick with `module`, I think a small adjustment to the matching of `function(` or async function(` would be a good improvement, especially if the docs requires a name.

WDYT?

**Comment by hsablonniere** [comment]
I just tried a very dumb and forgiving regex:

```
const FUNCTION_REGEX = /^(?:async )?function.*\(/;
```

and replaced the matching with this:

```
if(!trimmed.startsWith("module.exports = ")) {
  if(trimmed.match(FUNCTION_REGEX) != null) {
    content = `module.exports = ${content}`;
  }
}
```

It works pretty well.

**Comment by zachleat** [comment]
Well I closed this one way too fast! Yeah I really like the idea. I wonder if `acorn` might be worthwhile here, I’ve had good luck with that! I’d definitely merge a simple regex PR fix for now though—we can look at acorn later!

**Comment by zachleat** [comment]
Shipping with 0.2.0!

**Comment by hsablonniere** [comment]
Awesome! 🎉
