### ISSUE TITLE
How to pass non-string as prop?

### ISSUE THREAD

**Issue by pauleveritt** [11ty/webc#94]
If a parent component wants to pass some data to a child component -- a number, boolean, object, array -- how does one do this? It appears prop values are always treated as strings.

I can obviously create a StackBlitz or something if needed, but I think this is self-explanatory. I looked in the test stubs and the only uses of props were with string values.

**Comment by okmanideep** [comment]
Much needed quality of life improvement this

**Comment by okmanideep** [comment]
Just realised that this is possible for attributes. We can pass objects, arrays etc in attributes like `:tags="tags"` where `tags` is an array of strings.

Strange, considering attributes might affect the output unlike props.
> Props are “private” attributes that don’t end up in the output HTML (they are private to WebC). They are identical to attributes except that they are filtered from the output HTML.

**Comment by zachleat** [comment]
I think this was solved with #98, which introduced dynamic props via `:@propname`.

> WebC v0.9.0 will feature a new :@ prefix (e.g. :@value="tags.join(',')") for dynamic properties, thank you!
