### ISSUE TITLE
Unable to use js for prop values like attribute values

### ISSUE THREAD

**Issue by okmanideep** [11ty/webc#98]
👇 works - ✅ 
```html
<tags :value="tags.join(',')"></tags>
```

But 👇 does work - ❌ 
```html
<tags @value="tags.join(',')"></tags>
```

While we are at it, it will be great if we can [pass non strings as props](https://github.com/11ty/webc/issues/94), so we can just do this. Since props are just private to the webc runtime, this should not lead to any issues in the output.
```html
<tags @value="tags"></tags>
```

**Comment by zachleat** [comment]
WebC v0.9.0 will feature a new `:@` prefix (e.g. `:@my-name="tags.join(',')"`) for dynamic properties, thank you!
